from django.db import models

class Ngolist(models.Model):
    
    id = models.IntegerField(primary_key=True)
    NGO_Name = models.CharField(max_length=200)    
    Unique_Id_of_VO_NGO = models.CharField(max_length=200)
    Chief_Functionary = models.CharField(max_length=200)
    Chairman = models.CharField(max_length=200)
    Secretary = models.CharField(max_length=200)
    Treasurer = models.CharField(max_length=200)
    Promoter_Name_1 = models.CharField(max_length=200)
    Promoter_Name_2 = models.CharField(max_length=200)
    Promoter_Name_3 = models.CharField(max_length=200)
    Promoter_Name_4 = models.CharField(max_length=200)
    Umbrella_Parent_Organization = models.CharField(max_length=200)
    First_Registration_Details = models.CharField(max_length=200)
    Registered_With = models.CharField(max_length=200)
    Type_of_NGO = models.CharField(max_length=200)
    Registration_No = models.CharField(max_length=200)
    City_of_Registration = models.CharField(max_length=200)
    State_of_Registration = models.CharField(max_length=200)
    Date_of_Registration = models.CharField(max_length=200)
    Copy_of_Registration_Certificate = models.CharField(max_length=200)
    Second_Registration_Details = models.CharField(max_length=200)
    Third_Registration_Details = models.CharField(max_length=200)
    Sector_Key_Issues = models.CharField(max_length=200)
    Key_Issues = models.CharField(max_length=2000)
    Operational_Area_States = models.CharField(max_length=200)
    Details_of_Achievements = models.CharField(max_length=200)
    Major_Activities_Achievements = models.CharField(max_length=2000)
    Contact_Details = models.CharField(max_length=200)
    Address = models.CharField(max_length=2000)
    City = models.CharField(max_length=200)
    State = models.CharField(max_length=200)
    Telephone = models.CharField(max_length=200)
    misc = models.CharField(max_length=200)
    Mobile_No = models.CharField(max_length=200)
    E_mail = models.CharField(max_length=200)
    Operational_Area_District = models.CharField(max_length=200)
    Fax = models.CharField(max_length=200)
    FCRA_details = models.CharField(max_length=200)
    FCRA_Registration_no = models.CharField(max_length=200)
    Valid_up_to = models.CharField(max_length=200)
    Website_Url = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '{0}'.format(self.content)
    
    