# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngolist', '0002_auto_20150426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngolist',
            name='Address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Chairman',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='City',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='City_of_Registration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Contact_Details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Copy_of_Registration_Certificate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Date_of_Registration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Details_of_Achievements',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='E_mail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='FCRA_Registration_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='FCRA_details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Fax',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='First_Registration_Details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Key_Issues',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Major_Activities_Achievements',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Mobile_No',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='NGO_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Operational_Area_District',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Operational_Area_States',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Promoter_Name_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Promoter_Name_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Promoter_Name_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Promoter_Name_4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Registered_With',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Registration_No',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Second_Registration_Details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Secretary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Sector_Key_Issues',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='State',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='State_of_Registration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Telephone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Third_Registration_Details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Treasurer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Type_of_NGO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Umbrella_Parent_Organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Unique_Id_of_VO_NGO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Valid_up_to',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='Website_Url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngolist',
            name='misc',
            field=models.CharField(max_length=200),
        ),
    ]
